//
//  DataTest.swift
//  Traveldy
//
//  Created by Huong Nguyen on 4/13/21.
//

import Foundation

var homeData = HomeModel(
    banner: [
        Banner(id: 1, image: "ic_banner", link: ""),
        Banner(id: 2, image: "ic_banner2", link: ""),
        Banner(id: 3, image: "ic_banner", link: ""),
        Banner(id: 4, image: "ic_banner2", link: ""),
        Banner(id: 5, image: "ic_banner", link: ""),
    ],
    plan: Plan(id: "1", budget: 456.025, start: "2021-04-27T08:45:48.553Z", end: "2021-04-30T08:45:48.553Z", title: "Dubai", place: Place(placeName: "Burj Khalifa", longitude: 758.36, latitude: 800.25), status: "ONGOING", imgUrl: "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRPV746hNvcIPMAzc_lmdo8CSZwDTcFMjtr7k3AuKAaQQorwG2mwR60K4WrDMfTTw8dzhuZlWTuUx1TlBLE9SBy1A")
)

var dataForYou = [
    RecommendedTrip(id: 1,
                    image: "ic_bali",
                    name: "Balo",
                    location: "Indonesia 1",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "FORYOU",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 2,
                    image: "ic_bali",
                    name: "Balo",
                    location: "Indonesia 2",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "FORYOU",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 3,
                    image: "ic_bali",
                    name: "Balo",
                    location: "Indonesia 3",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "FORYOU",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 4,
                    image: "ic_bali",
                    name: "Balo",
                    location: "Indonesia 4",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "FORYOU",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 5,
                    image: "ic_bali",
                    name: "Balo",
                    location: "Indonesia 5",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "FORYOU",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
]

var dataHotPlaces = [
    RecommendedTrip(id: 1,
                    image: "ic_seoul",
                    name: "Seoul",
                    location: "Korea 1",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "HOTPLACES",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 2,
                    image: "ic_seoul",
                    name: "Seoul",
                    location: "Korea 2",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "HOTPLACES",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 3,
                    image: "ic_seoul",
                    name: "Seoul",
                    location: "Korea 3",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "HOTPLACES",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 4,
                    image: "ic_seoul",
                    name: "Seoul",
                    location: "Korea 4",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "HOTPLACES",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 5,
                    image: "ic_seoul",
                    name: "Seoul",
                    location: "Korea 5",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "HOTPLACES",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    
]

var dataDiscoverNew = [
    RecommendedTrip(id: 1,
                    image: "ic_park",
                    name: "Tongatio National Park 1",
                    location: "New Zealand",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "DISCOVERNEW",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 2,
                    image: "ic_park",
                    name: "Tongatio National Park 2",
                    location: "New Zealand",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "DISCOVERNEW",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 3,
                    image: "ic_park",
                    name: "Tongatio National Park 3",
                    location: "New Zealand",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "DISCOVERNEW",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 4,
                    image: "ic_park",
                    name: "Tongatio National Park 4",
                    location: "New Zealand",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "DISCOVERNEW",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
    RecommendedTrip(id: 5,
                    image: "ic_park",
                    name: "Tongatio National Park 5",
                    location: "New Zealand",
                    travelers: 1960,
                    content: "The Island of the Gods is rightly the most popular tourist destination in Indonesia. It’s the quintessential tropical paradise. Every day small offerings of flowers and burning incense sticks are left outside the hotels, bars and restaurants on the island. The gentle sound of a gong signals the passing of a parade of Balinese dressed in white robes. It is this rich culture, which has been enchanting tourists who come to the island for the last few hundred years.\nTourism in Bali is focused around the beaches and towns in the south of the island. Kuta attracts the young partygoers, Canggu has its hipsters, Ubud is where the yogis gather, Seminyak for the young and rich and Nusa Dua is where you go for your all inclusive 5 star resorts. It’s this diversity which makes Bali such an easy choice for a relaxing holiday.\nLeaving the city behind you are quickly surrounded by paddy fields and thick forested hills. The roads lead you through small villages and isolated temples perched on the slopes of the hills, the perfect place for a bicycle tour. In the highlands there are dozens of tumbling waterfalls where you can go for a swim, which lead into the rushing rivers where people go white water rafting. Or if you’re feeling adventurous you can spend your time jumping off waterfalls and abseiling on a day of canyoning.",
                    status: "DISCOVERNEW",
                    gallery: [
                        Banner(id: 1, image: "image6", link: ""),
                        Banner(id: 2, image: "image7", link: ""),
                        Banner(id: 3, image: "image8", link: ""),
                        Banner(id: 4, image: "image9", link: ""),
                        Banner(id: 5, image: "image11", link: ""),
                        Banner(id: 6, image: "image10", link: ""),
                        Banner(id: 7, image: "image12", link: ""),
                        Banner(id: 8, image: "image13", link: ""),
                        Banner(id: 9, image: "image1", link: ""),
                        Banner(id: 10, image: "image2", link: ""),
                        Banner(id: 11, image: "image3", link: ""),
                        Banner(id: 12, image: "image4", link: ""),
                        Banner(id: 13, image: "image5", link: "")
                    ]),
]
